
default: &default
  adapter: mysql2
  encoding: utf8

development:
  <<: *default
  database: lobsters
  host: postgres
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  database: lobsters
  host: postgres
  port: 5432
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

staging:
  <<: *default
  database: lobsters
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>

production:
  <<: *default
  database: lobsters_prod
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>





